name: uga
channels:
- r
- bioconda
- conda-forge
- mittner
- https://conda.anaconda.org/rmkoesterer
- defaults
dependencies:
- anaconda-client=1.1.2=py27_0
- biopython=1.66=np110py27_0
- cairo=1.12.18=5
- clyent=1.1.0=py27_0
- cython=0.23.4=py27_0
- demandimport=0.3.2=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0

- python=2.7
- numpy
- nomkl
- pandas
- psutil
- pysam=0.15.2
- rpy2
- scipy
- setuptools
- cython
- biopython
- progressbar
- r-base

ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1b               h7b6447c_1  
pip                       19.0.3                   py27_0  
pycosat                   0.6.3            py27h14c3975_0  
pycparser                 2.19                     py27_0  
pyopenssl                 19.0.0                   py27_0  
pysocks                   1.6.8                    py27_0  
python                    2.7.16               h9bab390_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py27_0  
ruamel_yaml               0.15.46          py27h14c3975_0  
setuptools                41.0.0                   py27_0  
six                       1.12.0                   py27_0  
sqlite                    3.27.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
urllib3                   1.24.1                   py27_0  
wheel                     0.33.1                   py27_0  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               h7b6447c_3  