name: uga
channels:
- https://conda.anaconda.org/rmkoesterer
- r
- defaults
- asmeurer
- bioconda
dependencies:
- anaconda-client=1.1.2=py27_0
- biopython=1.66=np110py27_0
- cairo=1.12.18=5
- clyent=1.1.0=py27_0
- cython=0.23.4=py27_0
- demandimport=0.3.2=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- glib=2.43.0=2
- harfbuzz=0.9.35=6
- hdf5=1.8.15.1=2
- jbig=2.1=0
- jpeg=8d=0
- libffi=3.0.13=0
- libgcc=4.8.5=1
- libgfortran=1.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- ncurses=5.9=5
- numexpr=2.4.4=np110py27_0
- numpy=1.10.1=py27_0
- openblas=0.2.14=3
- openssl=1.0.2f=0
- pandas=0.17.1=np110py27_0
- pango=1.36.8=3
- pcre=8.31=0
- pillow=3.0.0=py27_1
- pip=8.0.2=py27_0
- pixman=0.26.2=0
- progressbar=2.3=py27_0
- psutil=3.3.0=py27_0
- pysam=0.8.4=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- r-base=3.2.2=0
- r-r.utils=2.2.0=r3.2.2_0
- r-ggplot2=1.0.1=r3.2.2_0a
- r-lme4=1.1_9=r3.2.2_0a
- r-compquadform=1.4.1=r3.2.2_0
- r-coxme=2.2_5=r3.2.2_0
- r-kinship2=1.6.4=r3.2.2_0
- r-seqmeta=1.6.5=r3.2.2_0
- r-geepack=1.2_0.1=r3.2.2_0
- rpy2=2.7.4=py27r3.2.2_0
- readline=6.2.5=1
- requests=2.8.1=py27_0
- scipy=0.16.0=np110py27_1
- setuptools=19.6.2=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xlsxwriter=0.8.4=py27_0
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
