name: uga-docker-clone
channels:
- conda-forge
- bioconda
- r
- defaults
dependencies:
- python
- numpy
- nomkl
- pandas
- psutil
- pysam
- scipy
- setuptools
- cython
- biopython
- progressbar
- r-base
- rpy2
