name: uga
channels:
- conda-forge
- bioconda
- r
- defaults
dependencies:
- python=3.7.3
- numpy=1.16.4
- nomkl=3.0
- pandas=0.23.4
- psutil=5.6.3
- pysam=0.15.2
- scipy=1.3.0
- setuptools=41.0.1
- cython=0.29.12
- biopython=1.74
- progressbar=2.5
- r-base=3.5.1
- rpy2=2.9.4
